{% set name = "openlineage-sql" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openlineage_sql-{{ version }}.tar.gz
  sha256: b059363d9b1e70032cb106691e5d519047dcfc5e646ed11336642eb12d25f0fb

build:
  skip: true  # [py<310]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1                            # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1
    - pip
  run:
    - python

test:
  imports:
    - openlineage_sql
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python interface for the Rust OpenLineage lineage extraction library
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
