# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: openlineage-sql
  version: "1.39.0"
  maturin_min: "1.8.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/openlineage_sql-${{ version }}.tar.gz
  sha256: a8a30e8e96ae672e71ac598db438b3b2833a108b0d030f96f79e79a5e9264f31

build:
  number: 0
  # only build for the minimal python version
  #skip: not (match(python, python_min ~ ".*") and is_abi3) or match(python, ">=3.14")
  skip: match(python, ">=3.14")
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=${{ maturin_min }}
  host:
    - maturin >=${{ maturin_min }}
    - pip
    - python
    - python-abi3
  run:
    - python

tests:
  - python:
      imports: openlineage_sql
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - pytest >=8.2
        - pytest-cov >=5
        - pytest-mock >=3.14
        #- pip
        #- python !=${{ python_min }}.*
    script:
      - pip check
      - python -c "import openlineage_sql"

about:
  summary: Python interface for the Rust OpenLineage lineage extraction library
  homepage: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - millsks
